### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512]] is at version 8; expected version 7 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

### ISSUE THREAD

**Issue by rg321** [juntang-zhuang/torch_ACA#1]
getting above error when running code on server. dataset used is cifar-10 only with default option i.e. RK12. Stack trace given below ( with torch.autograd.set_detect_anomaly(True) ). Surprisingly code works fine on my laptop (but not on server). Any help would be appreciated -:

Training Epoch: #0, LR: 0.1000
Warning: Error detected in CudnnBatchNormBackward. Traceback of forward call that caused the error:
  File "train.py", line 235, in <module>
    train(_epoch)
  File "train.py", line 157, in train
    outputs = net(inputs)
  File "/home/cs19mtech11019/anaconda3/envs/mtvso/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cs19mtech11019/anaconda3/envs/mtvso/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/cs19mtech11019/anaconda3/envs/mtvso/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cs19mtech11019/cs19mtech11024/torch_ACA_mtvso/cifar_classification/models/resnet.py", line 109, in forward
    out = self.layer4_2(out)
  File "/home/cs19mtech11019/anaconda3/envs/mtvso/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cs19mtech11019/anaconda3/envs/mtvso/lib/python3.8/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/cs19mtech11019/anaconda3/envs/mtvso/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 91, in forward
    out = odesolve(self.odefunc, x, self.options, regenerate_graph = False)
  File "/home/cs19mtech11019/cs19mtech11024/torch_ACA_mtvso/torch_ACA/odesolver_mem/ode_solver_endtime.py", line 30, in odesolve_endtime
    z1 = solver.integrate(z0)#, t_eval = options['t_eval'])
  File "/home/cs19mtech11019/cs19mtech11024/torch_ACA_mtvso/torch_ACA/odesolver_mem/adaptive_grid_solver_endtime.py", line 307, in integrate
    y_current, error, variables = self.step(self.func, t_current, h_current * self.time_direction,
  File "/home/cs19mtech11019/cs19mtech11024/torch_ACA_mtvso/torch_ACA/odesolver_mem/adaptive_grid_solver_endtime.py", line 447, in step
    func2_temp = func(t + dt, y + 1.0 * k1)
  File "/home/cs19mtech11019/anaconda3/envs/mtvso/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cs19mtech11019/cs19mtech11024/torch_ACA_mtvso/cifar_classification/models/resnet.py", line 56, in forward
    out = self.bn2(out)
  File "/home/cs19mtech11019/anaconda3/envs/mtvso/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cs19mtech11019/anaconda3/envs/mtvso/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 103, in forward
    return F.batch_norm(
  File "/home/cs19mtech11019/anaconda3/envs/mtvso/lib/python3.8/site-packages/torch/nn/functional.py", line 1921, in batch_norm
    return torch.batch_norm(
 (print_stack at /opt/conda/conda-bld/pytorch_1591914886554/work/torch/csrc/autograd/python_anomaly_mode.cpp:60)
Traceback (most recent call last):
  File "train.py", line 235, in <module>
    train(_epoch)
  File "train.py", line 159, in train
    loss.backward()
  File "/home/cs19mtech11019/anaconda3/envs/mtvso/lib/python3.8/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/cs19mtech11019/anaconda3/envs/mtvso/lib/python3.8/site-packages/torch/autograd/__init__.py", line 98, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512]] is at version 8; expected version 7 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by rg321** [comment]
What I have found is, its working well with pytorch-cpu while it breaks for pytorch gpu version (even if I donot use a gpu).

**Comment by rg321** [comment]
works well with pytorch 1.3.1 (version cuda100py37h53c1284_0) but breaks with pytorch 1.5.1 (version py3.8_cuda10.1.243_cudnn7.6.3_0)

**Comment by juntang-zhuang** [comment]
Hi, thanks for the feedback. I only tested it with PyTorch 1.1 on my local machine with GPU, with CUDA 9.0, my machine cannot install a higher version of PyTorch due to the CUDA version. 
Is the bn layer defined in an in-place operation? It seems your model is re-defined, could you post the changes here?

**Comment by rg321** [comment]
I just re-arranged each operation in separate line, just to make sure that was not the cause of problem. Rest nothing is changed, but it turns out thats not the cause of error. For eg, 

**Original code was -:**
```
def forward(self,t, x):
        self.nfe += 1
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))
        #out += self.shortcut(x)
        out = F.relu(out)
        return out
```

**My code is -:**
```
def forward(self,t, x):
	self.nfe = self.nfe + 1
	out = self.conv1(x)
	out = self.bn1(out)
	out = F.relu(out)
	out = self.conv2(out)
	out = self.bn2(out)
	#out += self.shortcut(x)
	out = F.relu(out)
	return out
```

**Comment by rg321** [comment]
`hello`

**Comment by juntang-zhuang** [comment]
Seems to be a problem with some version update of PyTorch. I'm sorry I cannot help with it because I don't have the environment to install a new version of PyTorch. Perhaps you can keep using older version such as 1.3 or 1.1

**Comment by juntang-zhuang** [comment]
Hi, I tested with a CPU version of pytorch 1.6 (not on GPU due to CUDA version incompatibility), it seems to be a problem with using "load_state_dict" within a function to be backwarded through, and this issue happens with PyTorch1.5 and 1.6, it's ok with 1.4 and lower. The new pytorch tracks "version" of a tensor to restrict the use of in-place operation. A naive fix is to comment out all the "load_state_dict" in 'odesolver/adaptive_grid_solver.py' and 'odesolver_endtime/adaptive_grid_solver_endtime.py' and "odesolver_mem/adjoint_mem.py". 

The purpose of using load_state_dict is to fully recover the states of running statistics in batch norm layer, not loading it might cause some inaccuracy, depending on the data and model. BatchNorm use a fixed running statistic, however, in an ODE, using batchnorm is tricky, mainly because the ODE might drift, hence the batch statistics also varies with integration time, instead of static. 
One way to avoid this might be to use instance-norm of group-norm, rather than batch-norm. But I have not tested with experiments yet.

**Comment by rg321** [comment]
thanks for the response. i will confirm it as soon as i get a chance.

**Comment by rg321** [comment]
@juntang-zhuang I have commented out "load_state_dict" as suggested by you above but getting the same error (I am trying it on pytorch version 1.11).
